spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/H2DB/test;MODE=MYSQL
    username: sa

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: info
