spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: info

odsay:
  secret-key: gU/0UOBChjTBxg+fxexxWL43Rg/cFvbeAkx

jwt:
  secret-key: 52b50b2535067804540c89c9eec8359fa77b1a1845d7a0c3c97f3588d1f967c340b0e7c67d219bba1ee5bb008a996463c08c5a9d94cc95318aa1f57ec5149618
