version: "3"

services:
  react:
    restart: always
    command: npm start
    container_name: tp1
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3000"
    environment:
      - e CHOKIDAR_USEPOLLING=true
      # - NODE_ENV=development
    stdin_open: true
    tty: true